services:
  # 1. Service Python Data Science (IA)
  data-science:
    build:
      context: ../data-science/src
      dockerfile: Dockerfile
    container_name: python-data-science
    hostname: python-data-science
    ports:
      - "8000:8000"
    volumes:
      - ../data-science/Modelos:/app/Modelos
      - ../data-science/Modelos:/Modelos

    environment:
      - DJANGO_ENV=production
      - DJANGO_ALLOWED_HOSTS=python-data-science,localhost,127.0.0.1,*

  # 2. Backend Spring Boot (Oracle Autonomous Database)
  backend:
    build:
      context: ../backend-SpringBoot
      dockerfile: Dockerfile
    container_name: spring_backend
    ports:
      - "8080:8080"
    env_file:
      - ../backend-SpringBoot/.env
    volumes:
      - ../backend-SpringBoot/src/main/resources/wallet:/app/wallet
    environment:
      - DB_URL=${DB_URL:-jdbc:oracle:thin:@fincoachdb_high?TNS_ADMIN=/app/wallet}
      - DB_USER=${DB_USER:-ADMIN}
      - DB_PASS=${DB_PASS:-FinCoach2026!}
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
      - DS_SERVICE_URL=http://python-data-science:8000
    depends_on:
      - data-science

  # 3. Frontend Angular
  frontend:
    build:
      context: ../frontend-Angular
      dockerfile: Dockerfile
    container_name: angular_frontend
    ports:
      - "80:4000"
    env_file:
      - ../frontend-Angular/.env
    environment:
      - PORT=4000
      - JWT_SECRET=${JWT_SECRET:-FincoachG9LatamTeam14DevSecretKey2026MustBeAtLeast256BitsLong!!}
    depends_on:
      - backend