services:
  # Servidor de Base de Datos PostgreSQL (Único para todo el proyecto)
  postgres:
    image: postgres:16-alpine
    container_name: postgres_local
    environment:
      - POSTGRES_DB=finteligente_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Contenedor de Data Science
  data-science:
    build:
      context: ../data-science
      dockerfile: Dockerfile
    container_name: python_data_science
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=supersecretpassword123
      - DB_NAME=finteligente_db
    depends_on:
      - postgres

volumes:
  postgres_data: