services:
  # contenedor de MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql_local
    environment:
      - MYSQL_DATABASE=financiero
      - MYSQL_USER=postgres
      - MYSQL_PASSWORD=supersecretpassword123
      - MYSQL_ROOT_PASSWORD=supersecretrootpassword123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./fincoah_2026_07_18.sql:/docker-entrypoint-initdb.d/fincoah_2026_07_18.sql

  # contenedor de data-science
  data-science:
    build:
      context: ../../data-science
      dockerfile: Dockerfile
    container_name: python_data_science
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=postgres
      - DB_PASS=supersecretpassword123
      - DB_NAME=financiero
    depends_on:
      - mysql

volumes:
  mysql_data: